#!/bin/bash

if [ ! -d openhab/configurations ]; then
	echo "Fetching configuration..."
	# See: http://derekmolloy.ie/fixing-git-and-curl-certificates-problem-on-beaglebone-blac/
	git config --global http.sslVerify false
	git clone https://github.com/ronny-stauffer/yavanna-worben.git openhab/configurations
	echo "...done."
fi

echo "Starting Mosquitto..."
/etc/init.d/mosquitto start
echo "...done."

echo "Running openHAB..."
#/bin/bash
#. openhab/start.sh
openhab/start.sh
